### ISSUE TITLE
Invalid Exclude in Xcode 13

### ISSUE THREAD

**Issue by adam-redboxmobile** [Kitura/BlueCryptor#70] opened 2021-09-03 09:06 UTC
Since upgrading to Xcode 13, I'm seeing an Invalid Exclude warning message indicating that the requested file cannot be found.

This applies to:
- Cryptor.xcodeproj
- Sources/Info.plist
- README.md

**Comment by willm132** [comment] 2021-10-06 13:44
I am still getting this warning

**Comment by babbage** [comment] 2021-11-02 03:37
I am seeing this warning for files from BlueCryptor, BlueSocket and BlueSSLService, on Xcode 13.1 (13A1030d). The warnings are in all cases "Invalid Exclude... File not found."

For me, these are all dependencies that have been imported by another Swift Package—so it remains possible that it is a configuration issue from a package importing these projects that is the cause of the problem?

The affected files, all in Derived Data folder for SourcePackage checkouts, are:

_BlueCryptor_
BlueCryptor/Sources/Cryptor/README.md 
BlueCryptor/Sources/Cryptor/Sources/Info.plist 
BlueCryptor/Sources/Cryptor/Cryptor.xcodeproj

_BlueSocket_
BlueSocket/Sources/Socket/BlueSocket.xcodeproj
BlueSocket/Sources/Socket/BlueSocket.xcworkspace
BlueSocket/Sources/Socket/README.md
BlueSocket/Sources/Socket/Sources/Info.plist
BlueSocket/Sources/Socket/Sources/Socket.h

_BlueSSLService_
BlueSSLService/Sources/SSLService/SSLService.xcodeproj
BlueSSLService/Sources/SSLService/README.md
BlueSSLService/Sources/SSLService/Sources/Info.plist

**Comment by babbage** [comment] 2021-11-02 03:46
Ah—I saw elsewhere another project that was encountering this issue and it was associated with an older version of the Package being used. I see for my project, the package pulling in these packages listed above has set the v1 line as the dependency so only Cryptor 1.0.32 is being used. I am guessing that may be part of the issue?

**Comment by dannys42** [comment] 2021-11-02 04:14
@babbage Yes, that's probably it.  Is the parent package a Kitura repo?  If so, let me know and I'll take a look at resolving it.

**Comment by zntfdr** [comment] 2021-11-02 04:15
> If so, let me know and I'll take a look at resolving it.

@dannys42 please take a look at https://github.com/Kitura/Swift-JWT/pull/100, thank you :)

**Comment by babbage** [comment] 2021-11-02 04:26
> @babbage Yes, that's probably it. Is the parent package a Kitura repo? If so, let me know and I'll take a look at resolving it.

Turns out these are a dependency of Swift-SMTP, which is indeed a Kitura repo:
https://github.com/Kitura/Swift-SMTP

I checked and I am using the latest version of Swift-SMTP but it's dependencies specify:
```
    dependencies: [
        .package(url: "https://github.com/IBM-Swift/BlueSocket.git", from: "1.0.0"),
        .package(url: "https://github.com/IBM-Swift/BlueSSLService.git", from: "1.0.0"),
        .package(url: "https://github.com/IBM-Swift/BlueCryptor.git", from: "1.0.0"),
        .package(url: "https://github.com/IBM-Swift/LoggerAPI.git", from: "1.7.0"),
        ]
```

Thanks for taking a look at this. Awesome.

**Comment by babbage** [comment] 2021-11-02 04:29
Hmm, searching for dependencies that still specify IBM-Swift/* for these three repos might be a great way to track down other projects that may have the same outdated repos pinned as dependencies, I was thinking. :)

**Comment by dannys42** [comment] 2021-11-02 23:39
Thanks @babbage.  Yes there's a small number of projects that haven't been converted yet largely because they have more complicated testing dependencies (e.g. live servers, additional services, docker containers, etc.)  I'll see if I can take care of Swift-SMTP sometime soon though.

**Comment by MattTimmons** [comment] 2021-12-27 19:02
Any update on this?

**Comment by dannys42** [comment] 2021-12-28 18:08
@MattTimmons I just pushed a [PR for Swift-SMTP](https://github.com/Kitura/Swift-SMTP/pull/125) to address this.  I'm still working on getting the tests to work properly in CI.  But if you're able to try this out and run the unit tests successfully, I'll go ahead and tag/release.

**Comment by dannys42** [comment] 2021-12-29 01:17
@MattTimmons Ok the [PR for Swift-SMTP](https://github.com/Kitura/Swift-SMTP/pull/125) is now working.  Just waiting for code review.

**Comment by dannys42** [comment] 2021-12-31 18:08
@MattTimmons Please try release 6.0.0 of Swift-SMTP and let me know if it works for you.

**Comment by MattTimmons** [comment] 2021-12-31 23:19
YES! Works great for me. Using Docker for a Swift Linux build. I do have to have this in my docker file
`RUN yum -y install openssl-devel`
But everything built great. Thanks!

**Comment by dannys42** [comment] 2022-01-01 17:55
@adam-redboxmobile and others, can we consider this issue closed?

**Closed** 2022-01-04 10:47 UTC
